### PR TITLE
fix: point documentation to the right folder

### PR DESCRIPTION
**Pull request by wtrocki**
After moving docs to website folder some of the links in readme were broken. 
Simple change. 

## Verification

Load markdown view.
Inspect all the links that were changed.

### CODE REVIEW

**Comment by wtrocki** [comment]
I think it will be better to use website as reference rather than in repo readme files. 
WDYT? Happy to move this to website.

**Comment by rob3000** [comment]
Hey @wtrocki , 

Just in the process of updating the readme to point to the documentation website.

**Comment by wtrocki** [comment]
Ah.. sorry. Yep.. Closing

**Comment by wtrocki** [comment]
@rob3000 Since you haven't done it. I will merge this small change :)

**Pull request merged**
