### PR TITLE
Base config and file names.

### PR DESCRIPTION
**Pull request by rob3000**
Hi Guys, 

So after doing: https://github.com/nodefluent/node-sinek/pull/154 there was a lot to review. So this time i thought it would be easier to split it up. This is the first PR to move to typescript.
* Renamed files .js -> .ts
* Added eslint
* Fixed es6 import and exports.

Next steps:
* Fix actual types.
* Fix tests to work with typescript.

Apologies @wtrocki if i'm stepping on toes with this PR.

### CODE REVIEW

**Comment by wtrocki** [comment]
When renaming git will keep original history.
The way this changes were done it creates new files instead of renames. Also not the way I would suggest this to approach it. The best way IMHO will be to move one file at the time - with useJs: true.
Done migration many times. 
I have spent couple hours fixing tests and typings. You are free to take over this issue and contribute something meaningful, no problem, but -100 on approach in this PR.

**Comment by rob3000** [comment]
okay. will close this and approach this differently.

**Comment by wtrocki** [comment]
Perfect! Let's  collaborate on this no worries

**Comment by rob3000** [comment]
What's the best way to collaborate on this?

**Comment by wtrocki** [comment]
If you want to start fresh feel free to do so. There will be a lot of files to move so we can jump into those etc. Back from holidays next week

**Pull request closed without merging**
