### PR TITLE
Added base tsconfig.json. Moved files under src. 

### PR DESCRIPTION
**Pull request by rob3000**
Hey @wtrocki , 

From our discussion last week:
* Added base tsconfig.json to allowJS
* Moved JS files under Src
* Added eslint.

Next steps:
* Slowly replace the files to typescript.

### CODE REVIEW

**Comment by wtrocki** [comment]
Awesome work! So idea is to keep this branch open for now and collaborate? There are couple things that prevent us from merging this now. Is that ok?

**Comment by rob3000** [comment]
I'm open to either, keeping this open to collaborate or try to merge this, so that changes just get merged back to master.

If we take the latter approach, what would need fixing?

Force of habit, open to changing though.

**Comment by krystianity** [comment]
My suggestion on this whole merge strategy topic would be to have the chunks as small as possible (which can be quite hard sometimes especially when e.g. porting to ts) but have these in master as fast as possible and break it if necessary.

**Comment by rob3000** [comment]
I agree with @krstianity and will merge this in.

**Comment by wtrocki** [comment]
We merged that but this makes master unusable. There is no way to make any change as code will not compile and tests will not pass. Hoping to fix that now and add builds

**Pull request merged**
